version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - 3306
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - django_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  web:
    build: .
    container_name: django_app
    expose:
      - 8000
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    networks:
      - django_network
    command: >
      sh -c "python manage.py collectstatic --noinput &&
        python manage.py migrate &&
        gunicorn  --bind 0.0.0.0:8000 home_automation_server.wsgi:application"

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - web
    networks:
      - django_network

networks:
  django_network:
    driver: bridge

volumes:
  mysql_data:
  static_volume:
  media_volume:
